// <auto-generated />
using HC.Patient.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HC.Patient.Web.Migrations.HCMaster
{
    [DbContext(typeof(HCMasterContext))]
    [Migration("20200420110456_globalCode_GlobalCodeCategory")]
    partial class globalCode_GlobalCodeCategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HC.Patient.Entity.MasterAppConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<int>("ConfigType");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Key");

                    b.Property<string>("Label");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("MasterAppConfiguration");
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterAssessmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssessmentName");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("OrganizationId");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("MasterAssessmentType");
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterBenchmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("OrganizationId");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("MasterBenchmark");
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterCheckList", b =>
                {
                    b.Property<int>("CheckListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CheckListID");

                    b.Property<int>("CheckListCategoryID");

                    b.Property<string>("CheckListPoints")
                        .HasColumnType("varchar(500)");

                    b.Property<int>("CheckListPointsOrder");

                    b.Property<string>("CheckListType")
                        .HasColumnType("varchar(4)");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int>("DaysBeforeAndAfter");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("CheckListID");

                    b.HasIndex("CheckListCategoryID");

                    b.ToTable("MasterCheckList");
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterCheckListCategory", b =>
                {
                    b.Property<int>("CheckListCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CheckListCategoryID");

                    b.Property<string>("CategoryName")
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("CheckListCategoryID");

                    b.ToTable("MasterCheckListCategory");
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterDFA_Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("CategoryName");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<string>("Description");

                    b.Property<int?>("DisplayOrder");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("OrganizationID");

                    b.Property<decimal?>("PerfectScore");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationID");

                    b.ToTable("MasterDFA_Category");
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterDFA_CategoryCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<int>("CategoryId");

                    b.Property<string>("CodeName");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<string>("Description");

                    b.Property<int?>("DisplayOrder");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<decimal>("Score");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MasterDFA_CategoryCode");
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterDFA_Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<string>("Description");

                    b.Property<int?>("DisplayOrder");

                    b.Property<string>("DocumentName");

                    b.Property<int?>("DocumenttypeId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("MasterAssessmentTypeId");

                    b.Property<int>("OrganizationID");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("DocumenttypeId");

                    b.HasIndex("MasterAssessmentTypeId");

                    b.HasIndex("OrganizationID");

                    b.ToTable("MasterDFA_Document");
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterDFA_Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<int?>("DisplayOrder");

                    b.Property<int>("DocumentId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("SectionName");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("MasterDFA_Section");
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterDFA_SectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<int?>("CategoryId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<int?>("DisplayOrder");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ItemLabel");

                    b.Property<int>("Itemtype");

                    b.Property<int>("SectionId");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Itemtype");

                    b.HasIndex("SectionId");

                    b.ToTable("MasterDFA_SectionItem");
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterDiseaseManagementProgram", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("OrganizationId");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("OrganizationId");

                    b.ToTable("MasterDiseaseManagementProgram");
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterGlobalCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GlobalCodeID");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<int?>("DisplayOrder");

                    b.Property<int>("GlobalCodeCategoryID");

                    b.Property<string>("GlobalCodeName");

                    b.Property<string>("GlobalCodeValue");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("OrganizationID")
                        .IsRequired();

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("GlobalCodeCategoryID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("MasterGlobalCode");
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterGlobalCodeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GlobalCodeCategoryID");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<string>("GlobalCodeCategoryName");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("OrganizationID")
                        .IsRequired();

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationID");

                    b.ToTable("MasterGlobalCodeCategory");
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterOrganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OrganizationID");

                    b.Property<string>("Address1")
                        .HasMaxLength(200);

                    b.Property<string>("Address2")
                        .HasMaxLength(200);

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(20);

                    b.Property<string>("BusinessName")
                        .HasMaxLength(100);

                    b.Property<string>("City")
                        .HasMaxLength(100);

                    b.Property<string>("ContactPersonFirstName")
                        .HasMaxLength(50);

                    b.Property<string>("ContactPersonLastName")
                        .HasMaxLength(50);

                    b.Property<string>("ContactPersonMiddleName")
                        .HasMaxLength(50);

                    b.Property<string>("ContactPersonPhoneNumber")
                        .HasMaxLength(15);

                    b.Property<int?>("CountryID");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("DatabaseDetailId");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<string>("Email")
                        .HasMaxLength(250);

                    b.Property<string>("Favicon");

                    b.Property<string>("Fax")
                        .HasMaxLength(40);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<double?>("Latitude");

                    b.Property<string>("Logo");

                    b.Property<double?>("Longitude");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(100);

                    b.Property<string>("PayrollEndWeekDay")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PayrollStartWeekDay")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.Property<int?>("StateID");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<string>("VendorIdDirect")
                        .HasMaxLength(50);

                    b.Property<string>("VendorIdIndirect")
                        .HasMaxLength(50);

                    b.Property<string>("VendorNameDirect")
                        .HasMaxLength(250);

                    b.Property<string>("VendorNameIndirect")
                        .HasMaxLength(250);

                    b.Property<string>("Zip")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("MasterOrganization");
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterQuestionnaireBenchmarkRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BenchmarkId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<decimal>("MaxRange");

                    b.Property<decimal>("MinRange");

                    b.Property<int>("QuestionnaireId");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("BenchmarkId");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("MasterQuestionnaireBenchmarkRange");
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterSecurityQuestions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Question")
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("MasterSecurityQuestions");
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterSurveyCategory", b =>
                {
                    b.Property<int>("SurveyCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<string>("Description");

                    b.Property<int?>("DisplayOrder");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("OrganizationID");

                    b.Property<string>("SurveyCategoryName");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("SurveyCategoryID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("MasterSurveyCategory");
                });

            modelBuilder.Entity("HC.Patient.Entity.OrganizationDatabaseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(100);

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<bool>("IsCentralised");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Password")
                        .HasMaxLength(100);

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<string>("UserName")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("OrganizationDatabaseDetail");
                });

            modelBuilder.Entity("HC.Patient.Entity.SuperUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<DateTime?>("BlockDateTime");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBlock");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.Property<string>("Password");

                    b.Property<string>("RoleName");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("SuperUser");
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterAssessmentType", b =>
                {
                    b.HasOne("HC.Patient.Entity.MasterOrganization", "MasterOrganization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterBenchmark", b =>
                {
                    b.HasOne("HC.Patient.Entity.MasterOrganization", "MasterOrganization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterCheckList", b =>
                {
                    b.HasOne("HC.Patient.Entity.MasterCheckListCategory", "CheckListCategory")
                        .WithMany()
                        .HasForeignKey("CheckListCategoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterDFA_Category", b =>
                {
                    b.HasOne("HC.Patient.Entity.MasterOrganization", "MasterOrganization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterDFA_CategoryCode", b =>
                {
                    b.HasOne("HC.Patient.Entity.MasterDFA_Category", "MasterDFA_Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterDFA_Document", b =>
                {
                    b.HasOne("HC.Patient.Entity.MasterDiseaseManagementProgram", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumenttypeId");

                    b.HasOne("HC.Patient.Entity.MasterAssessmentType", "MasterAssessmentType")
                        .WithMany()
                        .HasForeignKey("MasterAssessmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HC.Patient.Entity.MasterOrganization", "MasterOrganization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterDFA_Section", b =>
                {
                    b.HasOne("HC.Patient.Entity.MasterDFA_Document", "MasterDFA_Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterDFA_SectionItem", b =>
                {
                    b.HasOne("HC.Patient.Entity.MasterDFA_Category", "MasterDFA_Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("HC.Patient.Entity.MasterDFA_CategoryCode", "MasterDFA_CategoryCode")
                        .WithMany()
                        .HasForeignKey("Itemtype")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HC.Patient.Entity.MasterDFA_Section", "MasterDFA_Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterDiseaseManagementProgram", b =>
                {
                    b.HasOne("HC.Patient.Entity.MasterOrganization", "MasterOrganization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterGlobalCode", b =>
                {
                    b.HasOne("HC.Patient.Entity.MasterGlobalCodeCategory", "MasterGlobalCodeCategory")
                        .WithMany()
                        .HasForeignKey("GlobalCodeCategoryID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HC.Patient.Entity.MasterOrganization", "MasterOrganization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterGlobalCodeCategory", b =>
                {
                    b.HasOne("HC.Patient.Entity.MasterOrganization", "MasterOrganization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterQuestionnaireBenchmarkRange", b =>
                {
                    b.HasOne("HC.Patient.Entity.MasterBenchmark", "MasterBenchmark")
                        .WithMany()
                        .HasForeignKey("BenchmarkId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HC.Patient.Entity.MasterDFA_Document", "DFA_Document")
                        .WithMany("MasterQuestionnaireBenchmarkRange")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HC.Patient.Entity.MasterSurveyCategory", b =>
                {
                    b.HasOne("HC.Patient.Entity.MasterOrganization", "MasterOrganization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
